---
- name: Add helm repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"
  
- name: helm install apache
  kubernetes.core.helm:
    name: apache
    namespace: default
    chart_ref: bitnami/apache

- name: helm install mongo
  kubernetes.core.helm:
    name: mongo
    namespace: default
    chart_ref: bitnami/mongodb


#- name: Deploy Grafana chart using values files on target
#  kubernetes.core.helm:
#    name: test
#    chart_ref: stable/grafana
#    release_namespace: monitoring
#    values_files:
#      - /path/to/values.yaml